artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/api/v1/datasets/download/mathchi/diabetes-data-set
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/diabetes.csv
  STATUS_FILE: artifacts/data_validation/status.txt